Improvements to keycloak theme
cph-cachet/carp-webservices-spring pull request #14
Opened 2023-12-06 11:15 UTC by SlimShadyIAm

Themed some more pages and fixed some text

2023-12-06 13:04 UTC, xelahalo approved these changes
i approve it but it's not like i like you or anything baka

2023-12-06 13:29 UTC, xelahalo requested changes

2023-12-06 13:36 UTC, xelahalo commented on keycloak-theme/src/login/pages/Info.stories.tsx
> +      requiredActions: ['UPDATE_PASSWORD'],
Can you also fix the PR name to reflect the changes made (not sg generic)

2023-12-06 21:51 UTC, SlimShadyIAm commented on keycloak-theme/src/login/pages/Info.stories.tsx
> +      requiredActions: ['UPDATE_PASSWORD'],
this is a mock for development

2024-03-04 12:17 UTC, xelahalo approved these changes

2024-03-04 12:18 UTC, merged